apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestcontext
  labels:
    app: requestcontext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requestcontext
  template:
    metadata:
      labels:
        app: requestcontext
    spec:
      containers:
        - name: requestcontext
          image: username/requestcontext:latest
          ports:
            - containerPort: 8080
          env:
            - name: LANGUAGE
              valueFrom:
                configMapKeyRef:
                  name: hello-cm
                  key: language
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
