apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestcontext
  labels:
    app: requestcontext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requestcontext
  template:
    metadata:
      labels:
        app: requestcontext
    spec:
      containers:
        - name: requestcontext
          image: username/requestcontext:latest
          ports:
            - containerPort: 8080
          env:
            - name: LANGUAGE
              valueFrom:
                configMapKeyRef:
                  name: hello-cm
                  key: language
