apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestContext
  labels:
    app: requestContext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requestContext
  template:
    metadata:
      labels:
        app: requestContext
    spec:
      containers:
        - name: requestContext
          image: username/requestContext:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
